# Generated by Django 3.2.9 on 2022-06-28 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=120)),
                ('teacher_direction', models.CharField(max_length=50, verbose_name="O'qituvchi yo'nalishi")),
            ],
            options={
                'verbose_name_plural': "O'qituvchilar haqida ma'lumot",
                'ordering': ['teacher_name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('course_description', models.TextField(max_length=700)),
                ('course_cost', models.PositiveIntegerField(default=0)),
                ('in_week', models.PositiveIntegerField(default=2)),
                ('time', models.CharField(max_length=13)),
                ('views', models.PositiveIntegerField(default=0)),
                ('course_photo', models.ImageField(upload_to='course-image/')),
                ('course_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AddtoCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kursga yozilganlar',
            },
        ),
    ]
