# Generated by Django 3.2.9 on 2022-08-01 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Kurslar'},
        ),
    ]
