# Generated by Django 3.2.9 on 2022-08-09 08:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0004_alter_course_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddtoCourse',
            new_name='Student',
        ),
    ]
