# Generated by Django 3.2.9 on 2022-08-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Describe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': "Maktab haqida ma'lumot",
            },
        ),
    ]
