# Generated by Django 3.2.9 on 2022-08-10 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20220809_1934'),
        ('base', '0008_auto_20220810_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_course_users', to='course.course'),
        ),
    ]
