# Generated by Django 3.2.9 on 2022-08-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_feedback_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
