# Generated by Django 3.2.9 on 2022-06-28 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='profile_photo',
            field=models.ImageField(blank=True, default='default-photo.jpg', upload_to='profile-photos/'),
        ),
        migrations.AddField(
            model_name='account',
            name='pupil_class',
            field=models.CharField(default='10 - B', max_length=8),
            preserve_default=False,
        ),
    ]
