# Generated by Django 3.2.9 on 2021-12-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ism')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Telefon raqam')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Elektron Pochta')),
            ],
        ),
    ]
