# Generated by Django 3.2.9 on 2021-12-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0002_auto_20211211_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Fan')),
                ('cost', models.CharField(max_length=50, verbose_name='Narx')),
                ('description', models.CharField(max_length=70, verbose_name='Tasvir')),
            ],
        ),
    ]
