# Generated by Django 3.2.9 on 2021-12-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0004_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(max_length=90, verbose_name='Tasvir'),
        ),
    ]
