# Generated by Django 3.2.9 on 2021-12-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0005_alter_lesson_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Matn')),
            ],
        ),
    ]
