# Generated by Django 3.2.9 on 2021-12-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0006_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Ism')),
                ('sourname', models.CharField(max_length=50, verbose_name='Familiya')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron Pochta')),
                ('address', models.CharField(max_length=150, verbose_name='Manzil')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Telefon Raqam')),
                ('message', models.TextField(verbose_name='Xabar')),
            ],
        ),
    ]
