# Generated by Django 3.2.9 on 2021-12-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0007_elements'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Elements',
            new_name='Element',
        ),
    ]
