# Generated by Django 3.2.9 on 2021-12-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0008_rename_elements_element'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
