# Generated by Django 3.2.9 on 2021-12-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0010_lesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
