# Generated by Django 3.2.9 on 2021-12-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0013_auto_20211214_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=70, verbose_name='Muallif')),
                ('meta', models.URLField(verbose_name='Meta')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('telegram', models.URLField(verbose_name='Telegram')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('about_author', models.TextField(verbose_name='Muallif haqida')),
            ],
        ),
    ]
