# Generated by Django 3.2.9 on 2021-12-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0015_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
