# Generated by Django 3.2.9 on 2021-12-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0017_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron Pochta')),
                ('date', models.DateField(verbose_name='Sana')),
                ('comment', models.TextField(verbose_name='Izoh')),
            ],
        ),
    ]
