# Generated by Django 3.2.9 on 2021-12-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0018_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Sana'),
        ),
    ]
