# Generated by Django 3.2.9 on 2021-12-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0019_alter_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron Pochta')),
                ('theme', models.CharField(max_length=150, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar matni')),
            ],
        ),
    ]
