# Generated by Django 3.2.9 on 2021-12-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0020_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='theme',
            field=models.CharField(max_length=200, verbose_name='Mavzu'),
        ),
    ]
