# Generated by Django 3.2.9 on 2021-12-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0021_alter_contact_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='theme',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mavzu'),
        ),
    ]
