# Generated by Django 3.2.9 on 2021-12-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0022_alter_contact_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopBlog',
        ),
    ]
