# Generated by Django 3.2.9 on 2021-12-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0023_delete_topblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('text', models.TextField(verbose_name='Matn')),
                ('date', models.DateField(verbose_name='Sana')),
                ('image', models.ImageField(upload_to='img')),
            ],
        ),
    ]
