# Generated by Django 3.2.9 on 2021-12-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0025_delete_addlesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Fan')),
                ('cost', models.CharField(max_length=50, verbose_name='Narx')),
                ('teacher_name', models.CharField(max_length=200, verbose_name="O'qituvchi ismi")),
                ('in_week', models.IntegerField(verbose_name='Haftada')),
                ('time', models.CharField(max_length=13, verbose_name="Vaqt oralig'")),
                ('description', models.CharField(max_length=90, verbose_name='Tasvir')),
                ('image', models.ImageField(upload_to='img')),
            ],
        ),
    ]
