# Generated by Django 3.2.9 on 2021-12-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0026_addlesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
