# Generated by Django 3.2.9 on 2021-12-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0028_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
