# Generated by Django 3.2.9 on 2021-12-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0029_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150, verbose_name='Ism')),
                ('meta', models.URLField(verbose_name='Meta')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('telegram', models.URLField(verbose_name='Telegram')),
                ('about_author', models.TextField(verbose_name='Muallif haqida')),
                ('image', models.ImageField(upload_to='img')),
            ],
        ),
    ]
