# Generated by Django 3.2.9 on 2022-01-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0031_remove_author_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
