# Generated by Django 3.2.9 on 2022-01-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0032_auto_20220127_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('text', models.TextField(verbose_name='Matn')),
                ('date', models.DateField(verbose_name='Sana')),
                ('image', models.ImageField(upload_to='img')),
                ('name', models.CharField(max_length=150, verbose_name='Ism')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron Pochta')),
                ('date_comment', models.DateField(blank=True, null=True, verbose_name='Sana')),
                ('comment', models.TextField(verbose_name='Izoh')),
            ],
        ),
    ]
