# Generated by Django 3.2.9 on 2022-01-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0033_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='comment',
            field=models.TextField(null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Elektron Pochta'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Ism'),
        ),
    ]
