# Generated by Django 3.2.9 on 2022-02-09 15:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0035_auto_20220127_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlesson',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='topblog',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
