# Generated by Django 3.2.9 on 2022-02-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0036_auto_20220209_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ism')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Elektron Pochta')),
                ('date_comment', models.DateField(blank=True, null=True, verbose_name='Sana')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='date_comment',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='email',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
    ]
