# Generated by Django 3.2.9 on 2022-02-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0037_auto_20220209_2038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
