# Generated by Django 3.2.9 on 2022-02-09 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0038_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ism')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Elektron Pochta')),
                ('date_comment', models.DateField(blank=True, null=True, verbose_name='Sana')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('choose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maktab_18.blog')),
            ],
        ),
    ]
