# Generated by Django 3.2.9 on 2022-03-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0039_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addlesson',
            options={'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'Muallif'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': 'Blog'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Izohlar'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Kontakt'},
        ),
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name_plural': 'Arizalar'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'Kurslarga yozilish'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name_plural': 'Obunalar'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name_plural': "Ma'lumot"},
        ),
        migrations.AlterModelOptions(
            name='topblog',
            options={'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AddField(
            model_name='addlesson',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
    ]
