# Generated by Django 3.2.9 on 2022-04-09 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0040_auto_20220306_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Fikrlar',
                'ordering': ['course'],
            },
        ),
        migrations.DeleteModel(
            name='TopBlog',
        ),
        migrations.RenameModel(
            old_name='AddLesson',
            new_name='Lesson',
        ),
        migrations.AddField(
            model_name='feedback',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maktab_18.lesson'),
        ),
    ]
