# Generated by Django 3.2.9 on 2022-04-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0041_auto_20220409_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_comment',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Sana'),
        ),
    ]
