# Generated by Django 3.2.9 on 2022-04-21 17:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0042_alter_comment_date_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_file', cloudinary.models.CloudinaryField(max_length=255)),
                ('photo', cloudinary.models.CloudinaryField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('exam_views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Imtixon savollari portali',
            },
        ),
    ]
