# Generated by Django 3.2.9 on 2022-04-21 17:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maktab_18', '0043_examquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
